osx_image: xcode7.2
language: objective-c

before_install:
- brew update
- brew install carthage
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- carthage update --platform iOS

script:
- xctool clean build -project Whisper.xcodeproj -scheme Whisper-iOS -sdk iphonesimulator
